### ISSUE TITLE
worksheet_write_string raises error for empty string string

### ISSUE THREAD

**Issue by jeroen** [jmcnamara/libxlsxwriter#121]
I found that `worksheet_write_string()` raises an error when inserting an empty string `""` value:

     NULL function parameter ignored.

In my data the empty string `""` is an actual value and different from no value `NULL`. Does Excel not support empty strings?

**Comment by jmcnamara** [comment]
> Does Excel support empty strings?

No. 

Excel ignores empty strings **unless** it has a format. This allows you to format blank cells as part of a formatted area. But blank or empty strings without formatting are never stored by Excel.

So libxlsxwriter returns an error/warning to let the user know that the parameter is being ignored.
However, the error probably isn't correct in this case since you aren't passing a `NULL`. It should probably say something like:

     Empty or NULL string without formatting is ignored.

I'll add a new warning for that.

**Comment by jeroen** [comment]
So the only way to store an empty string is make it e.g. bold?

**Comment by jmcnamara** [comment]
> So the only way to store an empty string is make it e.g. bold?

Yes. A empty string without formatting isn't stored by Excel. It just ignores them.

**Comment by jmcnamara** [comment]
> I'll add a new warning for that.

After thinking about this for a bit I've changed the code to just ignore unformatted empty or NULL strings without a warning/error. This is in line with what Excel does.
