### ISSUE TITLE
Is libxlsxwriter endian-safe?

### ISSUE THREAD

**Issue by cesss** [jmcnamara/libxlsxwriter#139]
Traditional Excel files depend on endianness, but maybe XLSX files don't (I don't know).

Can you confirm if libxlsxwriter should generate fine XLSX files both in big endian and little endian machines? (If affirmative, let me suggest adding this comment as a feature in the feature list)

**Comment by jmcnamara** [comment]
> Traditional Excel files depend on endianness, but maybe XLSX files don't (I don't know).

Correct. Xlsx files are XML files in a zip container so they aren't subject to endianess.



> Can you confirm if libxlsxwriter should generate fine XLSX files both in big endian and little endian machines?

I assume it should work on big endian systems but I can't confirm since I don't currently have access to a big-endian system (I used to have a Sun workstation). If you do you could [run the test suite](https://libxlsxwriter.github.io/running_the_tests.html) and confirm.

**Comment by cesss** [comment]
Yes, I do have access to an iMac G5. However, I cannot promise a date for the tests, as my access to that machine is not frequent.

**Comment by jmcnamara** [comment]
> I do have access to an iMac G5. 

Actually, I forgot that I have a G5 MacMini in my attic. If I get achance I'll dig it out for testing.

**Comment by jmcnamara** [comment]
I finally got around to booting up my old G5 Mac Mini to test this.

It was OS X 10.5.8 system and I hadn't used it since January 2011 according to the file times. It was still fairly usable though.

Anyway I compiled libxlsxwriter fine and the output file worked with Excel 2008 for Mac. After a bit of work I got a version of pytest to work with the system Python 2.5.1 and the test suite all passed except for one test with inserting a BMP image. I fixed that.

For the record you need to compile it as follows:

    make USE_BIG_ENDIAN=1

I've added this to the docs. Thanks for the prompt to try it.

**Comment by jmcnamara** [comment]
Added in version 0.7.6. Closing.
