### ISSUE TITLE
cmake compatibility

### ISSUE THREAD

**Issue by remicollet** [jmcnamara/libxlsxwriter#168]
Despite 

    cmake_minimum_required(VERSION 2.8.7)

It fails with cmake 2.8.12

```
CMake Error at CMakeLists.txt:171 (target_sources):
  Unknown CMake command "target_sources".

```

**Comment by jmcnamara** [comment]
@Alexhuszagh Can you take a look at this as well.

Or @remicollet can you submit a Pull Request.

**Comment by remicollet** [comment]
According to cmake changelog (in 3.1rst)
```

* The :command:`target_sources` command was added to add to the
  :prop_tgt:`SOURCES` target property.

```

**Comment by jmcnamara** [comment]
> The problem is that I'm not a cmake expert,

Neither am I. That's why @Alexhuszagh normally handles these issues.

I'm guessing that you are looking at this from the point of view of packaging. Is your preference to use cmake instead of make?

The make build system is still the primary build system for libxlsxwriter. Cmake is the secondary build system.

**Comment by remicollet** [comment]
> I'm guessing that you are looking at this from the point of view of packaging.
Yes

> Is your preference to use cmake instead of make?
No, but I notice a CMakeFile so I use cmake ;)
And I always consider as suspect a static Makefile (without cmake/autotools...)

**Comment by remicollet** [comment]
>    I'm guessing that you are looking at this from the point of view of packaging.

For your information I need this library for the upcoming new pecl extension [excel-writer](https://github.com/viest/php-ext-excel-export)  which offers bindings for this library

And if everything works as expected, RPM for Fedora / RHEL / CentOS will be available in my [repository ](http://rpms.remirepo.net/) which is mostly provides PHP stuff, but is also an incubator for official  Fedora/EPEL repositories.

**Comment by Alexhuszagh** [comment]
FYI, @jmcnamara, I like @remicollet's commit with very minor,  minor exceptions. I'm hoping to have a fix later today:
https://github.com/remicollet/libxlsxwriter/commit/80ceba65a9cbdf42d5b83612587a150de563dddd

**Comment by Alexhuszagh** [comment]
@remicollet Good catch on the `target_sources`, I updated the library generation a few months ago but forgot to test the minimum version. My fault, very well done.

**Comment by Alexhuszagh** [comment]
The main issue now with multi-arch is the fact that `-m32` can be passed to the CMake flags if intentionally aiming to build a 32-bit library on a 64-bit system, but this will still install to lib64.

The proper, CMake way to do this would likely be to have a separate toolchain for 32-bit toolchain that specifies the proper CMake system processor, and then could be used during project configuration, rather than "Just another option" would be to add a toolchain file for 32-bit code generation.

This correctly tells CMake that the compiler is 32-bit, not 64-bit, updates the system name, and allows Cmake to correctly determine an installation path of `lib` or `lib64` as a resylt.

I'll also update the CMake documentation as a result.

**Comment by jmcnamara** [comment]
P.S. @remicollet and @Alexhuszag. Thanks for the input. In future PRs can you avoid putting defect numbers in the subject line. You can put them in the body of the commit message.
