### ISSUE TITLE
Does libxlsxwriter have print out to paper function?

### ISSUE THREAD

**Issue by liufeijin** [jmcnamara/libxlsxwriter#198]
I can 't find the print out function in the .h file
?

**Comment by jmcnamara** [comment]
What function/ option is this called in Excel?

**Comment by liufeijin** [comment]
I want to print out excel file on paper after filling data to a excel by libxlsxwriter.
I want to do this in my app , and don't want to open the file by excel and print out it.

**Comment by jmcnamara** [comment]
> I want to do this in my app , and don't want to open the file by excel and print out it.

So, if I understand you want to print out the Excel file after you create it.

That isn't something that the library can handle since it isn't a part of the file format. It is something that is done at a system level. It is the same as if you had a PDF, DOCX or even TXT file.

So this isn't a feature that can be implemented by the library.

Closing.
