### ISSUE TITLE
Saving workbook without closing it.

### ISSUE THREAD

**Issue by IhdeneMalek** [jmcnamara/libxlsxwriter#236]
Hey, Is there a possibility of adding a save function to save the workbook without closing it? I'd be happy to implement it if it's not already out there, is it even possible to implement?

**Comment by jmcnamara** [comment]
For context, what is your use case for this feature.

> Is there a possibility of adding a save function to save the workbook without closing it?

Technically it is possible, it just involves creating and overwriting the xlsx file each time. However, I don't plan to add it since it wasn't part of the initial design and adding it now would require a lot of testing and would probably introduce a lot of edge cases/bugs.

Libxlsxwriter is a port of the Python module [XlsxWriter ](https://github.com/jmcnamara/XlsxWriter)which in turn is a port of the Perl module [Excel::Writer::XLSX](https://github.com/jmcnamara/excel-writer-xlsx), all of which I wrote and maintain. So a new feature needs to be added to the Perl versions first, then to the Python version, and then to the C version. So unfortunately this is a "won't implement" for me.
