### ISSUE TITLE
Output stream support and example table styles

### ISSUE THREAD

**Issue by punisher97** [jmcnamara/libxlsxwriter#249]
Hi i testing your wonderful library, I will build my own port xlsxwriter in Nodejs, but i need output stream as in [Python](https://xlsxwriter.readthedocs.io/example_django_simple.html), to attach with [Express](https://expressjs.com/es/starter/hello-world.html) in Nodejs, other hand side i need create table with style like [this](https://xlsxwriter.readthedocs.io/example_tables.html#example-worksheet-tables)

I share [my initial repo](https://github.com/punisher97/xlsxwriter4node) with port in Nodejs to help in future any, currently only execute the hello world example    ![Nodejs](https://camo.githubusercontent.com/5442dc3af3fd83011c59bad0d09fcf1b66fc59a5/68747470733a2f2f70756e697368657239372e6769746875622e696f2f786c7378777269746572346e6f64652f6173736574732f64656d6f2e706e67)

Thanks!

**Comment by jmcnamara** [comment]
Thanks that looks cool.

Could you add libxlsxwriter as a "topic" metadata to your project so that users can find wrappers in different languages.

Topic/Metadata are shown at the top of the project: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

> i need output stream as in Python

That isn't currently supported. There is a currently a feature request for it (#196) but I don't know how it can be done in a portable way.

> i need create table with style like this

There is also a feature request for that (#33). That will be added at some stage.

Closing this issue since the requests are covered in other feature requests.
