### ISSUE TITLE
The macro "SLIST_ENTRY" is redefined

### ISSUE THREAD

**Issue by ZChidori** [jmcnamara/libxlsxwriter#250]
Question:The macro "SLIST_ENTRY" is redefined in winnt.h and third_party/queue.h,how to fix it?

**Comment by jmcnamara** [comment]
What compiler and version are you using and what is your compilation target?

See also #57

**Comment by ZChidori** [comment]
VS2008 and libxlsxwriter-release-0.8.7

**Comment by ZChidori** [comment]
Well,my vs environment don't have base.h.

**Comment by jmcnamara** [comment]
Are you trying to compile for WinNT?

Also,  if you ignore the warning does the compilation work?

**Comment by ZChidori** [comment]
No,doesn't affect my use,I just want to solve it.In any case,thanks.

**Comment by jmcnamara** [comment]
Are you trying to compile for WinNT?

**Comment by jmcnamara** [comment]
The `SLIST_ENTRY` Windows macro should be undefined by libxlsxwriter to avoid this issue. See:

https://github.com/jmcnamara/libxlsxwriter/blob/master/src/packager.c#L40

Since your overall compilation works I presume this code is included so I'm not sure why you are getting the warning. 

Try add the following before you use `#include "xlsxwriter.h"`:

```C
#undef SLIST_ENTRY
```
