### ISSUE TITLE
Sizes and margins of images in Header and Footer

### ISSUE THREAD

**Issue by vic7tar** [jmcnamara/libxlsxwriter#308]
Hello.
Mr. McNamara, can you add functionality to position and resize images in headers and footers? In Excel VBA, these are the **.LeftHeaderPicture, .CenterHeaderPicture … .RightFooterPicture** properties of the **PageSetup** object.

**Comment by jmcnamara** [comment]
It is possible to resize a header/footer image but I don't think it is possible to position them. At least I can't see anything in the Excel menus/properties to do that.

However, even though resizing would be possible it isn't something that anyone else has asked for (even in the Perl and Python versions) and it would clutter the API (since it would require 3 lxw_image_options (or similar) pointers for 
the 3 header zones. Also, it is relatively easy to just scale the image outside of Libxlsxwriter.

So overall this is a "won't fix" for me. Sorry.
