### ISSUE TITLE
Adjust Cell Width in Xcode

### ISSUE THREAD

**Issue by willm132** [jmcnamara/libxlsxwriter#326]
I just got this working in my iOS app and it works great, the only issue I am running into is setting the cell width. 

I am using this code:

let cellWidth = 25.0
let row = 0
let column = 0
worksheet_set_column(worksheet1, row, column, cellWidth, standardText)

and I have changed 25 to other numbers but the cell width is not changing once the document is created.

**Comment by jmcnamara** [comment]
> I just got this working in my iOS app and it works great

Cool. Does that mean I can close the Swift Package Manager request?

> the only issue I am running into is setting the cell width.

I don't know what is happening. Unfortunately I don't use Swift (or Xcode very much) but the equivalent C program works fine:

```C
#include "xlsxwriter.h"

int main() {

    /* Create a workbook and add a worksheet. */
    lxw_workbook  *workbook  = workbook_new("test.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    /* Adjust the column width. */
    worksheet_set_column(worksheet, 0, 0, 25, NULL);

    return workbook_close(workbook);
}
```

Output:

![screenshot](https://user-images.githubusercontent.com/94267/115536422-ae1c9b00-a291-11eb-8f3a-11b2d8fd2094.png)

Note, the syntax of [worksheet_set_column()](https://libxlsxwriter.github.io/worksheet_8h.html#a9656e4e05d3787eee6b3e4d8e82d9b7f) is (column, column) not (row, column), although in your case they are both 0 so that isn't the issue.

John

**Comment by willm132** [comment]
Yes you may close them
