### ISSUE TITLE
question: <The picture shows the wrong scale>

### ISSUE THREAD

**Issue by totaldmis** [jmcnamara/libxlsxwriter#363]
### Question

Hello Sir,
I am using VC2019 to test the "xlsxwriter" library. I compiled the example project and executed the example program "images.exe". The program produced the "images.xlsx" file. When I opened the "images.xlsx" file with Excel 2019, I found There is a problem with the display ratio of the picture in the file. For example, the first picture does not have a zoom ratio set in the program, but it displays 90% width and 110% height in excel. What is the problem?

I am using VC2019 X64, Windows 10 and Excel 2019.

It is the example code and the xlsx file:
[images.zip](https://github.com/jmcnamara/XlsxWriter/files/7778964/images.zip)
![Scale1](https://user-images.githubusercontent.com/77141948/147447415-7e1600f8-208d-4a56-88b7-347e21e422e7.png)

In addition, the font used in Excel is Chinese Song Ti. Maybe it's an error caused by the font?
![Scale2](https://user-images.githubusercontent.com/77141948/147447489-6c801f54-251f-4185-874b-245bf071d590.png)

thank you very much

**Comment by jmcnamara** [comment]
Transferred issue to the libxlsxwriter Github.

**Comment by jmcnamara** [comment]
Probably there is some other system setting where the default font is set. Setting the default font in Excel won't change the font when you are reading files.

Can you try with this test file created in Excel and see if you get the same behaviour: https://github.com/jmcnamara/libxlsxwriter/blob/main/test/functional/xlsx_files/image10.xlsx

**Comment by jmcnamara** [comment]
Any update on this?

**Comment by totaldmis** [comment]
Sorry, I haven't noticed your reply these days. I tested your file. It seems that there is still the same problem. Please see my screen copy. Note, this time I am using the Chinese version of Excel.
![QQ截图20220104145934](https://user-images.githubusercontent.com/77141948/148021919-96cdfabb-c87e-46d6-a84d-17a29a55ba83.png)
.

**Comment by jmcnamara** [comment]
That file was created in Excel. So this issue isn't related to libxlsxwriter (which produces the same file and dimensions as Excel).

I don't any good suggestions on  how to deal with this:

- You could scale the image in libxlsxwriter so that it is 100% x100% in Excel but this will distort the image if you share it with anyone with a non Chinese version of Excel.
- Change the system font used by Excel - however this would probably effect other programs as well do that probably isn't a good solution.

Any way this isn't a libxlsxwriter issue. Libxlsxwriter has a lot of code and tests to ensure that it inserts images in exactly the same way as Excel.

So, since I cannot help you any further I will close this issue.
