### ISSUE TITLE
Add SPM Support

### ISSUE THREAD

**Issue by mariohahn** [jmcnamara/libxlsxwriter#369]
In addition to Cocopods it would be great to also support Swift Package Manager.

Thx for the lib. 🎸

https://github.com/jmcnamara/libxlsxwriter/issues/325

**Comment by jmcnamara** [comment]
There is already a Swift package for libxlsxwriter: https://swiftpackageregistry.com/damuellen/xlsxwriter.swift

**Comment by jmcnamara** [comment]
@mariohahn Is the linked package sufficient. Can this request be closed?

**Comment by jmcnamara** [comment]
Closing.

**Comment by willm132** [comment]
> There is already a Swift package for libxlsxwriter: https://swiftpackageregistry.com/damuellen/xlsxwriter.swift

This does not work or compile so that is not sufficient

**Comment by jmcnamara** [comment]
@willm132 You need to take that up with the Swift Package maintainer.

**Comment by orchetect** [comment]
Just FYI: the release tags for the repo are not compatible with SPM. Which greatly limits the ability to use the library as a Swift package. SPM looks for SemVer tags (ie: "1.1.7"), so it won't understand "RELEASE_1.1.7"

If the library is used as a dependency in an app then it may be possible to just use main branch. But It cannot be used as a dependency within another Swift package because Xcode will not compile, citing an unstable dependency.

The easiest resolution would be to tag the repo as SemVer instead of "RELEASE_x.x.x". If that's not viable, then tagging the repo twice would work fine, one tag as SemVer and the other as "RELEASE_x.x.x".

**Comment by jmcnamara** [comment]
> SPM looks for SemVer tags (ie: "1.1.7"), so it won't understand "RELEASE_1.1.7"

Does it have to be "1.1.7" or can it be "v1.1.7".

**Comment by orchetect** [comment]
> Does it have to be "1.1.7" or can it be "v1.1.7".

Ideally "1.1.7", but "v1.1.7" is also recognized.
