### ISSUE TITLE
How to set custom theme?

### ISSUE THREAD

**Issue by Paxa** [jmcnamara/libxlsxwriter#95]
As I see `workbook_close` will always call `_write_theme_file` and it will always read `theme_strs`

Is there a way to override default theme?

**Comment by jmcnamara** [comment]
It isn't possible to set the theme in my Perl/Python/C/Lua libraries. Mainly because changing the theme also changes the fonts and the default row and column sizes associated with them. This in turn affect the size calculations for inserted objects such as images or charts.

It may be something that is supported one day but it isn't on any of the shorter term roadmaps.
